CREATE TABLE BRANDS
(
    ID   INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(63) NOT NULL
);

CREATE TABLE PRICES
(
    PRICE_LIST INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID   INT NOT NULL,
    START_DATE TIMESTAMP,
    END_DATE   TIMESTAMP,
    PRODUCT_ID INT,
    PRIORITY   INT,
    PRICE DOUBLE,
    CURR       VARCHAR(7),
    CONSTRAINT FK_BRANDS FOREIGN KEY (BRAND_ID) REFERENCES BRANDS (ID)
);
