version: '3'

services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../:/app
    command: [ "./gradlew", "clean", "build", "bootRun" ]
    environment:
      - DATABASE_H2_USERNAME=sa
      - DATABASE_H2_PASSWORD=password
      - H2_CONSOLE=true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health-check" ]
      interval: 1m
      timeout: 10s
      retries: 3
